(define (third_func first_int second_int third_int)
  (if ( > first_int second_int) 
    (+ ( * first_int first_int) 
      (if ( > second_int third_int)
        ( *  second_int second_int)
        ( * third_int third_int)
      )
    )
    (if ( > first_int third_int)
      (+ ( * first_int first_int) 
        (if ( > second_int third_int) 
          ( * second_int second_int)
          ( * third_int third_int)))
      ( + ( * second_int second_int) 
        ( * third_int third_int)
      )
    )
  )
)